version: '3'

services:
  postgres:
    container_name: todo_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
#   volumes:
#     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
